controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

fc_load_events:
    path: /fc-load-events
    defaults:
        _controller: CalendarBundle\Controller\CalendarController::loadAction